# Generated by Django 2.1.5 on 2020-09-08 06:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Activity',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(help_text='活动标题', max_length=500, null=True, verbose_name='活动标题')),
                ('description', models.CharField(help_text='简要介绍', max_length=1000, null=True, verbose_name='简要介绍')),
                ('content', models.TextField(help_text='活动内容', null=True, verbose_name='活动内容')),
                ('img', models.ImageField(help_text='活动图片', null=True, upload_to='active', verbose_name='活动图片')),
                ('date', models.DateField(auto_now_add=True, help_text='发布时间', null=True, verbose_name='发布时间')),
                ('begin', models.DateField(help_text='活动开始时间', null=True, verbose_name='活动开始时间')),
                ('over', models.DateField(help_text='活动结束时间', null=True, verbose_name='活动结束时间')),
                ('is_show', models.BooleanField(default=True, help_text='是否展示在小程序', verbose_name='是否上架')),
            ],
            options={
                'verbose_name': '活动信息',
                'verbose_name_plural': '活动信息',
                'ordering': ('-date',),
            },
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.CharField(help_text='订单号', max_length=20, verbose_name='订单号')),
                ('unionId', models.CharField(help_text='用户标识', max_length=20, verbose_name='用户标识')),
                ('remarks', models.CharField(help_text='订单备注', max_length=500, verbose_name='订单备注')),
                ('status', models.BooleanField(default=False, help_text='订单状态，付款还是未付款', verbose_name='订单状态')),
                ('is_fail', models.BooleanField(default=False, help_text='超过时间未付款,或者其他状态订单失效', verbose_name='订单是否失效')),
                ('is_send', models.BooleanField(default=False, help_text='是否发货', verbose_name='是否发货')),
                ('is_over', models.BooleanField(default=False, help_text='此订单是否完成', verbose_name='此订单是否完成')),
                ('is_show', models.BooleanField(default=True, help_text='用户删除不做物理删除,是否向用户展示', verbose_name='是否删除')),
                ('quantity', models.IntegerField(default=1, help_text='商品数量', verbose_name='数量')),
                ('money', models.FloatField(help_text='支付金额', verbose_name='支付金额')),
                ('virtualMoney', models.FloatField(help_text='萌度兑换支付', verbose_name='萌度支付')),
                ('is_virtual', models.BooleanField(default=True, help_text='是否支持萌度兑换', verbose_name='是否支持萌度兑换')),
                ('date', models.DateTimeField(auto_now_add=True, help_text='订单创建时间', verbose_name='订单创建时间')),
            ],
            options={
                'verbose_name': '订单管理',
                'verbose_name_plural': '订单管理',
                'ordering': ('-date',),
            },
        ),
        migrations.CreateModel(
            name='ProductImg',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('img', models.ImageField(help_text='商品图片', null=True, upload_to='product', verbose_name='商品展示图')),
                ('property', models.IntegerField(default=0, help_text='属性等级', verbose_name='属性等级')),
                ('is_show', models.BooleanField(default=True, help_text='是否展示在商城', verbose_name='是否上架')),
            ],
            options={
                'verbose_name': '商品图片',
                'verbose_name_plural': '商品图片',
            },
        ),
        migrations.CreateModel(
            name='ProductInfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='商品名称', max_length=400, verbose_name='商品名称')),
                ('price', models.FloatField(help_text='商品单价', verbose_name='单价')),
                ('virtual', models.FloatField(help_text='萌度兑换需要的价格', verbose_name='萌度兑换需要的单价')),
                ('quantity', models.IntegerField(help_text='商品总数', verbose_name='数量')),
                ('sail', models.IntegerField(default=0, help_text='卖出数量', verbose_name='卖出数量')),
                ('property', models.IntegerField(default=0, help_text='商品属性等级, 支持支付方式,萌度,现金,余额', verbose_name='商品属性')),
                ('date', models.DateTimeField(auto_now_add=True, help_text='创建时间', verbose_name='创建时间')),
                ('is_show', models.BooleanField(default=True, help_text='是否展示在商城', verbose_name='是否上架')),
                ('discount', models.FloatField(default=1.0, help_text='打几折', verbose_name='折扣')),
                ('is_discount', models.BooleanField(default=False, help_text='是否打折', verbose_name='是否打折')),
            ],
            options={
                'verbose_name': '商品信息',
                'verbose_name_plural': '商品信息',
            },
        ),
        migrations.AddField(
            model_name='productimg',
            name='product',
            field=models.ForeignKey(help_text='商品', on_delete=django.db.models.deletion.CASCADE, related_name='productImg', to='mini.ProductInfo', verbose_name='商品'),
        ),
        migrations.AddField(
            model_name='order',
            name='product',
            field=models.ForeignKey(help_text='商品', on_delete=django.db.models.deletion.CASCADE, to='mini.ProductInfo', verbose_name='商品'),
        ),
    ]
