# Generated by Django 2.1.5 on 2020-09-08 18:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mini', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='activity',
            name='is_show',
            field=models.BooleanField(choices=[(False, '未删除'), (True, '删除')], default=True, help_text='是否展示在小程序', verbose_name='是否上架'),
        ),
        migrations.AlterField(
            model_name='order',
            name='is_fail',
            field=models.BooleanField(choices=[(False, '订单失效'), (True, '订单正常')], default=False, help_text='超过时间未付款,或者其他状态订单失效', verbose_name='订单是否失效'),
        ),
        migrations.AlterField(
            model_name='order',
            name='is_over',
            field=models.BooleanField(choices=[(False, '订单未完成'), (True, '订单完成')], default=False, help_text='此订单是否完成', verbose_name='此订单是否完成'),
        ),
        migrations.AlterField(
            model_name='order',
            name='is_send',
            field=models.BooleanField(choices=[(False, '订单未发货'), (True, '订单已发货')], default=False, help_text='是否发货', verbose_name='是否发货'),
        ),
        migrations.AlterField(
            model_name='order',
            name='is_show',
            field=models.BooleanField(choices=[(False, '未删除'), (True, '删除')], default=False, help_text='用户删除不做物理删除,是否向用户展示', verbose_name='是否删除'),
        ),
        migrations.AlterField(
            model_name='order',
            name='is_virtual',
            field=models.BooleanField(choices=[(False, '不支持萌度'), (True, '支持萌度')], default=True, help_text='是否支持萌度兑换', verbose_name='是否支持萌度兑换'),
        ),
        migrations.AlterField(
            model_name='productimg',
            name='is_show',
            field=models.BooleanField(choices=[(False, '未删除'), (True, '删除')], default=True, help_text='是否展示在商城', verbose_name='是否上架'),
        ),
        migrations.AlterField(
            model_name='productinfo',
            name='is_discount',
            field=models.BooleanField(choices=[(False, '不打折'), (True, '打折')], default=False, help_text='是否打折', verbose_name='是否打折'),
        ),
        migrations.AlterField(
            model_name='productinfo',
            name='property',
            field=models.IntegerField(choices=[(False, '不打折'), (True, '打折')], default=0, help_text='商品属性等级, 支持支付方式,萌度,现金,余额', verbose_name='商品属性'),
        ),
    ]
