# Generated by Django 2.1.5 on 2020-09-14 07:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mini', '0002_auto_20200908_1813'),
    ]

    operations = [
        migrations.AlterField(
            model_name='activity',
            name='is_show',
            field=models.BooleanField(choices=[(False, '未删除'), (True, '删除')], default=False, help_text='是否展示在小程序', verbose_name='是否上架'),
        ),
        migrations.AlterField(
            model_name='productimg',
            name='is_show',
            field=models.BooleanField(choices=[(False, '未删除'), (True, '删除')], default=False, help_text='是否展示在商城', verbose_name='是否上架'),
        ),
        migrations.AlterField(
            model_name='productinfo',
            name='is_show',
            field=models.BooleanField(choices=[(False, '未删除'), (True, '删除')], default=False, help_text='是否展示在商城', verbose_name='是否上架'),
        ),
        migrations.AlterField(
            model_name='productinfo',
            name='property',
            field=models.IntegerField(choices=[(0, '支持萌度/微信/余额支付'), (1, '不支持萌度支付'), (2, '仅支持微信/支付宝/银行卡支付')], default=0, help_text='商品属性等级, 支持支付方式,萌度,现金,余额', verbose_name='商品属性'),
        ),
        migrations.AlterField(
            model_name='productinfo',
            name='virtual',
            field=models.FloatField(blank=True, help_text='萌度兑换需要的价格', verbose_name='萌度兑换需要的单价'),
        ),
    ]
