# Generated by Django 2.1.5 on 2020-09-23 05:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('mini', '0003_auto_20200914_1511'),
    ]

    operations = [
        migrations.CreateModel(
            name='ShoppingCat',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('unionId', models.CharField(help_text='用户', max_length=20, verbose_name='用户')),
                ('num', models.IntegerField(help_text='数量', verbose_name='数量')),
                ('create_time', models.DateTimeField(auto_now_add=True, help_text='添加时间', verbose_name='添加时间')),
                ('is_show', models.BooleanField(choices=[(False, '未删除'), (True, '删除')], default=False, help_text='是否失效', verbose_name='是否失效')),
                ('product', models.ForeignKey(help_text='商品', on_delete=django.db.models.deletion.CASCADE, related_name='catProduct', to='mini.ProductInfo', verbose_name='商品')),
            ],
            options={
                'verbose_name': '购物车',
                'verbose_name_plural': '购物车',
                'ordering': ('-create_time',),
            },
        ),
    ]
