# Generated by Django 2.1.5 on 2020-09-23 05:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mini', '0004_shoppingcat'),
    ]

    operations = [
        migrations.AddField(
            model_name='shoppingcat',
            name='status',
            field=models.BooleanField(default=True, help_text='商品数量是否满足', verbose_name='状态'),
        ),
        migrations.AlterField(
            model_name='shoppingcat',
            name='is_show',
            field=models.BooleanField(choices=[(False, '未删除'), (True, '删除')], default=False, help_text='是否删除', verbose_name='是否删除'),
        ),
    ]
