# Generated by Django 2.1.5 on 2020-09-23 06:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mini', '0005_auto_20200923_1356'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='product',
        ),
        migrations.AddField(
            model_name='order',
            name='product',
            field=models.ManyToManyField(help_text='商品', to='mini.ProductInfo', verbose_name='商品'),
        ),
    ]
