# Generated by Django 2.1.5 on 2020-09-23 06:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mini', '0006_auto_20200923_1407'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='quantity',
        ),
        migrations.AlterField(
            model_name='order',
            name='product',
            field=models.ManyToManyField(help_text='商品', to='mini.ShoppingCat', verbose_name='商品'),
        ),
    ]
