# Generated by Django 2.1.5 on 2020-09-24 07:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mini', '0007_auto_20200923_1424'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='product',
            field=models.ManyToManyField(help_text='购物车', to='mini.ShoppingCat', verbose_name='购物车'),
        ),
    ]
