# Generated by Django 2.1.5 on 2020-10-15 06:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mini', '0008_auto_20200924_1531'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='is_fail',
            field=models.BooleanField(choices=[(False, '订单正常'), (True, '订单失效')], default=False, help_text='超过时间未付款,或者其他状态订单失效', verbose_name='订单是否失效'),
        ),
        migrations.AlterField(
            model_name='order',
            name='money',
            field=models.FloatField(default=0, help_text='支付金额', verbose_name='支付金额'),
        ),
        migrations.AlterField(
            model_name='order',
            name='number',
            field=models.CharField(help_text='订单号', max_length=200, verbose_name='订单号'),
        ),
        migrations.AlterField(
            model_name='order',
            name='remarks',
            field=models.CharField(blank=True, default='', help_text='订单备注', max_length=500, verbose_name='订单备注'),
        ),
        migrations.AlterField(
            model_name='order',
            name='unionId',
            field=models.CharField(help_text='用户标识', max_length=200, verbose_name='用户标识'),
        ),
        migrations.AlterField(
            model_name='order',
            name='virtualMoney',
            field=models.FloatField(default=0, help_text='萌度兑换支付', verbose_name='萌度支付'),
        ),
        migrations.AlterField(
            model_name='shoppingcat',
            name='unionId',
            field=models.CharField(help_text='用户', max_length=100, verbose_name='用户'),
        ),
    ]
