# Generated by Django 2.1.5 on 2020-10-14 08:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mini', '0009_auto_20200930_1152'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='number',
            field=models.CharField(help_text='订单号', max_length=200, verbose_name='订单号'),
        ),
        migrations.AlterField(
            model_name='order',
            name='remarks',
            field=models.CharField(blank=True, help_text='订单备注', max_length=500, verbose_name='订单备注'),
        ),
        migrations.AlterField(
            model_name='order',
            name='unionId',
            field=models.CharField(help_text='用户标识', max_length=200, verbose_name='用户标识'),
        ),
    ]
