# Generated by Django 2.1.5 on 2020-10-14 09:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mini', '0010_auto_20201014_1620'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='is_fail',
            field=models.BooleanField(choices=[(False, '订单正常'), (True, '订单失效')], default=False, help_text='超过时间未付款,或者其他状态订单失效', verbose_name='订单是否失效'),
        ),
        migrations.AlterField(
            model_name='order',
            name='money',
            field=models.FloatField(default=0, help_text='支付金额', verbose_name='支付金额'),
        ),
        migrations.AlterField(
            model_name='order',
            name='remarks',
            field=models.CharField(blank=True, default='', help_text='订单备注', max_length=500, verbose_name='订单备注'),
        ),
        migrations.AlterField(
            model_name='order',
            name='virtualMoney',
            field=models.FloatField(default=0, help_text='萌度兑换支付', verbose_name='萌度支付'),
        ),
    ]
