# Generated by Django 2.1.5 on 2020-10-22 07:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mini', '0009_auto_20201015_1407'),
        ('mini', '0011_auto_20201014_1715'),
    ]

    operations = [
    ]
