# Generated by Django 2.1.5 on 2020-11-17 08:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mini', '0012_merge_20201022_1535'),
    ]

    operations = [
        migrations.AlterField(
            model_name='activity',
            name='description',
            field=models.BooleanField(default=False, help_text='是否置顶', verbose_name='是否置顶'),
        ),
    ]
