# Generated by Django 2.1.5 on 2020-11-26 05:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0013_address_is_default'),
        ('mini', '0016_auto_20201125_1259'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='address',
            field=models.ForeignKey(blank=True, help_text='收货地址', null=True, on_delete=django.db.models.deletion.CASCADE, to='user.Address', verbose_name='收货地址'),
        ),
    ]
