# Generated by Django 2.1.5 on 2020-12-01 07:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Image',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('img', models.ImageField(blank=True, help_text='网站小程序等图片', null=True, upload_to='game', verbose_name='图片')),
            ],
            options={
                'verbose_name': '网站图片库',
                'verbose_name_plural': '网站图片库',
            },
        ),
    ]
