# Generated by Django 2.1.5 on 2020-12-04 06:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0002_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='image',
            name='img',
            field=models.ImageField(blank=True, help_text='网站小程序等图片,场景图横：812*375，竖：331*587,头像-二维码:120*120', null=True, upload_to='game', verbose_name='图片'),
        ),
    ]
