# Generated by Django 2.1.5 on 2020-09-14 07:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('analy', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='analysis',
            options={'verbose_name': '数据分析', 'verbose_name_plural': '数据分析'},
        ),
        migrations.AlterField(
            model_name='analysis',
            name='url',
            field=models.URLField(blank=True, help_text='可视化结果地址', verbose_name='分析结果可视化'),
        ),
    ]
