# Generated by Django 2.1.5 on 2020-09-14 07:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('analy', '0002_auto_20200914_1516'),
    ]

    operations = [
        migrations.AlterField(
            model_name='analysis',
            name='url',
            field=models.FileField(help_text='分析结果', upload_to='', verbose_name='地址'),
        ),
    ]
