# Generated by Django 2.1.5 on 2020-09-14 08:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('voice', '0002_auto_20200914_1622'),
    ]

    operations = [
        migrations.AlterField(
            model_name='voice',
            name='url',
            field=models.FileField(blank=True, help_text='音频地址', null=True, unique=True, upload_to='voice', verbose_name='链接'),
        ),
    ]
