# Generated by Django 2.1.5 on 2020-09-16 04:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('voice', '0003_auto_20200914_1623'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='voice',
            options={'verbose_name': '音频', 'verbose_name_plural': '音频'},
        ),
    ]
