# Generated by Django 2.1.5 on 2020-12-24 09:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('voice', '0004_auto_20200916_1219'),
    ]

    operations = [
        migrations.AddField(
            model_name='voice',
            name='language',
            field=models.IntegerField(choices=[(1, '中文'), (2, '英文')], default=1, help_text='转换语言', verbose_name='转换语言'),
        ),
        migrations.AddField(
            model_name='voice',
            name='sound',
            field=models.IntegerField(choices=[(0, '默认声音'), (5, '中度声音'), (9, '大声一点')], default=5, help_text='说话声音大小', verbose_name='说话声音'),
        ),
        migrations.AlterField(
            model_name='voice',
            name='human',
            field=models.IntegerField(blank=True, default=101016, help_text='说话人可选', null=True, verbose_name='说话人'),
        ),
    ]
