# Generated by Django 2.1.5 on 2021-01-06 07:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('voice', '0005_auto_20201224_1748'),
    ]

    operations = [
        migrations.AlterField(
            model_name='voice',
            name='human',
            field=models.IntegerField(blank=True, choices=[(0, '云小宁-女'), (1, '云小奇-男'), (101015, '智萌-男孩'), (101016, '智甜-女孩')], default=101016, help_text='说话人可选', null=True, verbose_name='说话人'),
        ),
    ]
