# Generated by Django 2.1.5 on 2020-09-08 05:44

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='GameInfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('grade', models.CharField(blank=True, default='1', help_text='等级', max_length=20, null=True, verbose_name='等级')),
                ('score', models.CharField(blank=True, default='0', help_text='得分', max_length=20, null=True, verbose_name='得分')),
                ('level', models.CharField(blank=True, default='1', help_text='关卡', max_length=50, null=True, verbose_name='关卡')),
                ('property', models.CharField(blank=True, default='0', help_text='金币钻石资源', max_length=100, null=True, verbose_name='金币钻石资源')),
                ('is_subscription', models.BooleanField(default=False, help_text='是否接受订阅，默认关闭', verbose_name='是否订阅')),
                ('ortherInfo', models.TextField(default='', help_text='其它数据', verbose_name='其它数据')),
            ],
            options={
                'verbose_name': '用户游戏信息',
                'verbose_name_plural': '用户游戏信息',
            },
        ),
        migrations.CreateModel(
            name='MengYou_knowlage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('img', models.ImageField(help_text='学习图片', null=True, upload_to='MengYou', verbose_name='图片')),
                ('title', models.CharField(help_text='标题', max_length=500, null=True, verbose_name='标题')),
                ('voice', models.URLField(blank=True, help_text='此知识的语音数据', null=True, verbose_name='音频数据')),
                ('text', models.TextField(help_text='文本内容', null=True, verbose_name='文本内容')),
                ('level', models.CharField(default='1', help_text='学习等级', max_length=50, verbose_name='此条知识适合学习的等级')),
                ('need', models.CharField(default='1', help_text='学习所需时间,小时单位，请填写多少小时,默认为1', max_length=10, verbose_name='时间')),
                ('is_check', models.BooleanField(default=False, help_text='是否审核过,False 未审核，待审核,True 已经审核过', verbose_name='是否经过审核')),
                ('status', models.BooleanField(default=False, help_text='审核状态，false未通过，True通过', verbose_name='审核状态')),
            ],
            options={
                'verbose_name': '萌游知知，知识数据',
                'verbose_name_plural': '萌游知知，知识数据',
            },
        ),
        migrations.CreateModel(
            name='MengYou_recoding',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_over', models.BooleanField(default=False, help_text='学习状态', verbose_name='是否学习完毕')),
                ('send_time', models.DateTimeField(help_text='订阅消息时间', null=True, verbose_name='发送订阅消息时间')),
                ('game_info', models.ForeignKey(help_text='学习状态与游戏角色绑定', on_delete=django.db.models.deletion.CASCADE, to='games.GameInfo', verbose_name='外键关系')),
                ('knowlage', models.ForeignKey(help_text='游戏角色与知识id绑定有此条记录说明该角色学习过或正在学习', on_delete=django.db.models.deletion.CASCADE, related_name='knowlage_recod', to='games.MengYou_knowlage', verbose_name='知识id')),
            ],
            options={
                'verbose_name': '萌游知知，学习记录',
                'verbose_name_plural': '萌游知知，学习记录',
            },
        ),
        migrations.CreateModel(
            name='Sign',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField(default=django.utils.timezone.now, help_text='记录签到时间', verbose_name='签到时间')),
                ('game_info', models.ForeignKey(help_text='签到状态与游戏角色绑定', on_delete=django.db.models.deletion.CASCADE, to='games.GameInfo', verbose_name='外键关系')),
            ],
            options={
                'verbose_name': '签到记录',
                'verbose_name_plural': '签到记录',
            },
        ),
    ]
