# Generated by Django 2.1.5 on 2020-09-08 18:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('games', '0002_auto_20200908_1344'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gameinfo',
            name='is_subscription',
            field=models.BooleanField(choices=[(False, '不接受订阅'), (True, '接受订阅')], default=False, help_text='是否接受订阅，默认关闭', verbose_name='是否订阅'),
        ),
        migrations.AlterField(
            model_name='mengyou_knowlage',
            name='is_check',
            field=models.BooleanField(choices=[(False, '未审核'), (True, '已经审核')], default=False, help_text='是否审核过,False 未审核，待审核,True 已经审核过', verbose_name='是否经过审核'),
        ),
        migrations.AlterField(
            model_name='mengyou_knowlage',
            name='status',
            field=models.BooleanField(choices=[(False, '不通过'), (True, '通过')], default=False, help_text='审核状态，false未通过，True通过', verbose_name='审核状态'),
        ),
        migrations.AlterField(
            model_name='mengyou_recoding',
            name='is_over',
            field=models.BooleanField(choices=[(False, '未完成学习'), (True, '完成学习')], default=False, help_text='学习状态', verbose_name='是否学习完毕'),
        ),
    ]
