# Generated by Django 2.1.5 on 2020-09-09 17:24

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('games', '0003_auto_20200908_1813'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='mengyou_knowlage',
            options={'verbose_name': '萌游知知，知识审核', 'verbose_name_plural': '萌游知知，知识审核'},
        ),
        migrations.AlterField(
            model_name='gameinfo',
            name='game_id',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='user.APP', verbose_name='游戏'),
        ),
        migrations.AlterField(
            model_name='gameinfo',
            name='user_id',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='用户'),
        ),
        migrations.AlterField(
            model_name='mengyou_recoding',
            name='game_info',
            field=models.ForeignKey(help_text='学习状态与游戏角色绑定', on_delete=django.db.models.deletion.CASCADE, to='games.GameInfo', verbose_name='学习用户'),
        ),
        migrations.AlterField(
            model_name='mengyou_recoding',
            name='knowlage',
            field=models.ForeignKey(help_text='游戏角色与知识id绑定有此条记录说明该角色学习过或正在学习', on_delete=django.db.models.deletion.CASCADE, related_name='knowlage_recod', to='games.MengYou_knowlage', verbose_name='知识'),
        ),
        migrations.AlterField(
            model_name='mengyou_recoding',
            name='send_time',
            field=models.DateTimeField(help_text='学习完成时间', null=True, verbose_name='发送订阅消息时间'),
        ),
        migrations.AlterField(
            model_name='sign',
            name='game_info',
            field=models.ForeignKey(help_text='签到状态与游戏角色绑定', on_delete=django.db.models.deletion.CASCADE, to='games.GameInfo', verbose_name='签到用户'),
        ),
    ]
