# Generated by Django 2.1.5 on 2020-10-15 06:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('games', '0004_auto_20200909_1724'),
    ]

    operations = [
        migrations.CreateModel(
            name='Diray',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('img', models.ImageField(blank=True, help_text='日记图片', null=True, upload_to='MengShang', verbose_name='图片')),
                ('text', models.TextField(help_text='日记内容', null=True, verbose_name='日记内容')),
                ('date', models.DateTimeField(auto_now_add=True, help_text='日记时间', verbose_name='日记时间')),
                ('title', models.CharField(help_text='日记标题', max_length=200, verbose_name='日记标题')),
                ('weather', models.IntegerField(blank=True, choices=[(0, '晴天'), (1, '多云'), (2, '雨天')], help_text='天气状态', null=True, verbose_name='天气状态')),
                ('mood', models.IntegerField(blank=True, choices=[(0, '开心'), (1, '平静'), (2, '生气'), (3, '伤心'), (4, '委屈')], help_text='心情状态', null=True, verbose_name='心情状态')),
                ('public', models.BooleanField(choices=[(False, '不公开'), (True, '公开')], default=True, help_text='是否公开', verbose_name='是否公开')),
                ('status', models.BooleanField(choices=[(False, '未删除'), (True, '删除')], default=False, help_text='是否删除', verbose_name='是否删除')),
                ('game_info', models.ForeignKey(help_text='日记与游戏角色绑定', on_delete=django.db.models.deletion.CASCADE, to='games.GameInfo', verbose_name='日记用户')),
            ],
            options={
                'verbose_name': '萌上日记,日记库',
                'verbose_name_plural': '萌上日记,日记库',
            },
        ),
        migrations.CreateModel(
            name='Mailbox',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.BooleanField(choices=[(False, '未删除'), (True, '删除')], default=False, help_text='是否删除', verbose_name='是否删除')),
                ('date', models.DateTimeField(auto_now_add=True, help_text='日记进入时间', verbose_name='日记进入时间')),
                ('favor', models.BooleanField(choices=[(False, '不收藏'), (True, '收藏')], default=False, help_text='是否收藏', verbose_name='是否收藏')),
                ('diray', models.ForeignKey(help_text='日记', on_delete=django.db.models.deletion.CASCADE, to='games.Diray', verbose_name='日记')),
                ('game_info', models.ForeignKey(help_text='信箱与游戏角色绑定', on_delete=django.db.models.deletion.CASCADE, to='games.GameInfo', verbose_name='日记用户')),
            ],
            options={
                'verbose_name': '萌上日记,信箱',
                'verbose_name_plural': '萌上日记,信箱',
            },
        ),
    ]
