# Generated by Django 2.1.5 on 2020-09-08 17:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0002_auto_20200908_1713'),
    ]

    operations = [
        migrations.AlterField(
            model_name='myuser',
            name='is_auth',
            field=models.BooleanField(choices=[(False, '未授权'), (True, '授权')], default=False, help_text='是否被授权', verbose_name='是否被授权'),
        ),
    ]
