# Generated by Django 2.1.5 on 2020-09-08 18:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0004_auto_20200908_1724'),
    ]

    operations = [
        migrations.AlterField(
            model_name='address',
            name='is_show',
            field=models.BooleanField(choices=[(False, '未删除'), (True, '删除')], default=True, help_text='用户删除不做物理删除', verbose_name='是否删除'),
        ),
    ]
