# Generated by Django 2.1.5 on 2020-09-21 09:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0007_auto_20200916_1544'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userip',
            name='count',
            field=models.IntegerField(default=1, verbose_name='访问次数'),
        ),
    ]
