# Generated by Django 2.1.5 on 2020-10-22 07:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0010_auto_20200928_1753'),
        ('user', '0010_auto_20201015_1407'),
    ]

    operations = [
    ]
