# Generated by Django 2.1.5 on 2020-10-22 07:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0011_merge_20201022_1535'),
    ]

    operations = [
        migrations.AddField(
            model_name='userip',
            name='name',
            field=models.CharField(default='unknow', help_text='name', max_length=200, verbose_name='用户'),
        ),
    ]
