# Generated by Django 2.1.5 on 2020-12-01 04:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0013_address_is_default'),
    ]

    operations = [
        migrations.AddField(
            model_name='app',
            name='on_line',
            field=models.CharField(choices=[('0', '不启用'), ('1', '启用')], default='0', max_length=20, verbose_name='是否启动'),
        ),
    ]
