# Generated by Django 2.1.5 on 2020-12-01 05:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0014_app_on_line'),
    ]

    operations = [
        migrations.AddField(
            model_name='recordlogin',
            name='game',
            field=models.ForeignKey(blank=True, help_text='游戏', null=True, on_delete=django.db.models.deletion.CASCADE, to='user.APP', verbose_name='游戏'),
        ),
    ]
