# Generated by Django 2.1.5 on 2020-12-24 09:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0015_recordlogin_game'),
    ]

    operations = [
        migrations.AlterField(
            model_name='app_config',
            name='orther',
            field=models.CharField(blank=True, choices=[('0', '网站信息设置'), ('1', '分享信息设置'), ('2', '启动参数设置'), ('3', '广告信息设置')], help_text='其他', max_length=100, null=True, verbose_name='其他'),
        ),
    ]
