# Generated by Django 2.1.5 on 2021-01-06 07:10

import datetime
from django.db import migrations, models
import django.db.models.deletion
from django.utils.timezone import utc


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('user', '0016_auto_20201224_1748'),
        ('games', '0007_advertising'),
    ]

    operations = [
        migrations.CreateModel(
            name='Mail',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(help_text='邮件标题', max_length=300, verbose_name='邮件标题')),
                ('date', models.DateTimeField(default=datetime.datetime(2021, 1, 6, 7, 10, 35, 287473, tzinfo=utc), help_text='邮件时间', verbose_name='邮件时间')),
                ('text', models.TextField(help_text='邮件内容', verbose_name='邮件内容')),
                ('online', models.IntegerField(choices=[(0, '显示'), (1, '不显示')], default=0, help_text='个人邮件', verbose_name='个人邮件是否删除')),
                ('game_info', models.ForeignKey(help_text='信箱与游戏角色绑定', on_delete=django.db.models.deletion.CASCADE, to='games.GameInfo', verbose_name='日记用户')),
            ],
            options={
                'verbose_name_plural': '个人邮件',
            },
        ),
        migrations.CreateModel(
            name='SysMail',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(help_text='邮件标题', max_length=300, verbose_name='邮件标题')),
                ('date', models.DateTimeField(default=datetime.datetime(2021, 1, 6, 7, 10, 35, 288676, tzinfo=utc), help_text='邮件时间', verbose_name='邮件时间')),
                ('until_date', models.DateTimeField(help_text='邮件过期时间', verbose_name='过期时间')),
                ('text', models.TextField(help_text='邮件内容', verbose_name='邮件内容')),
                ('online', models.IntegerField(choices=[(0, '显示'), (1, '不显示')], default=0, help_text='个人邮件', verbose_name='个人邮件是否删除')),
                ('type', models.IntegerField(choices=[(0, '在线奖励'), (1, '所有人奖励')], default=0, help_text='系统邮件类型', verbose_name='系统邮件类型')),
                ('game', models.ForeignKey(help_text='选择游戏', on_delete=django.db.models.deletion.CASCADE, to='user.APP', verbose_name='选择游戏')),
                ('game_info', models.ManyToManyField(help_text='信箱与游戏角色绑定', to='games.GameInfo', verbose_name='日记用户')),
            ],
            options={
                'verbose_name_plural': '系统邮件',
            },
        ),
    ]
