# Generated by Django 2.1.5 on 2021-01-06 07:36

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('mail', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='mail',
            options={'verbose_name': '个人邮件', 'verbose_name_plural': '个人邮件'},
        ),
        migrations.AlterModelOptions(
            name='sysmail',
            options={'verbose_name': '系统邮件', 'verbose_name_plural': '系统邮件'},
        ),
        migrations.RemoveField(
            model_name='sysmail',
            name='online',
        ),
        migrations.AlterField(
            model_name='mail',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2021, 1, 6, 7, 36, 1, 154305, tzinfo=utc), help_text='邮件时间', verbose_name='邮件时间'),
        ),
        migrations.AlterField(
            model_name='sysmail',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2021, 1, 6, 7, 36, 1, 155505, tzinfo=utc), help_text='邮件时间', verbose_name='邮件时间'),
        ),
    ]
