# Generated by Django 2.1.5 on 2021-01-08 03:29

import datetime
from django.db import migrations, models
import django.db.models.deletion
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('mail', '0002_auto_20210106_1536'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mail',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2021, 1, 8, 3, 29, 6, 249310, tzinfo=utc), help_text='邮件时间', verbose_name='邮件时间'),
        ),
        migrations.AlterField(
            model_name='mail',
            name='game_info',
            field=models.ForeignKey(help_text='邮件与游戏角色绑定', on_delete=django.db.models.deletion.CASCADE, to='games.GameInfo', verbose_name='邮件用户'),
        ),
        migrations.AlterField(
            model_name='sysmail',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2021, 1, 8, 3, 29, 6, 251548, tzinfo=utc), help_text='邮件时间', verbose_name='邮件时间'),
        ),
        migrations.AlterField(
            model_name='sysmail',
            name='game_info',
            field=models.ManyToManyField(help_text='邮件与游戏角色绑定', to='games.GameInfo', verbose_name='邮件用户'),
        ),
    ]
