# Generated by Django 2.1.5 on 2020-09-09 17:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('job', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='jobs',
            name='jobType',
            field=models.CharField(choices=[('date', '定时一次任务'), ('interval', '周期任务'), ('cron', 'corn任务')], default='date', help_text='任务类型', max_length=10, verbose_name='任务类型'),
        ),
        migrations.AlterField(
            model_name='jobs',
            name='name',
            field=models.CharField(choices=[('send_mes', '发送订阅消息'), ('change_status', '修改学习状态'), ('test', '测试代码')], default='send_mes', help_text='任务名称，描述任务做什么的', max_length=200, verbose_name='任务名称'),
        ),
        migrations.AlterField(
            model_name='jobs',
            name='parameters',
            field=models.CharField(help_text='所需参数', max_length=2000, null=True, verbose_name='参数'),
        ),
    ]
