# Generated by Django 2.1.5 on 2020-09-10 13:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('job', '0004_auto_20200910_1306'),
    ]

    operations = [
        migrations.AlterField(
            model_name='jobs',
            name='parameters',
            field=models.CharField(default=None, help_text='所需参数', max_length=2000, null=True, verbose_name='参数'),
        ),
    ]
