# Generated by Django 2.1.5 on 2020-09-10 08:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('job', '0005_auto_20200910_1306'),
    ]

    operations = [
        migrations.CreateModel(
            name='Job',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('case_id', models.CharField(help_text='任务名', max_length=200, verbose_name='任务队列')),
                ('next_run', models.DateTimeField(help_text='下次执行时间', null=True, verbose_name='下次执行时间')),
                ('parameters', models.CharField(help_text='参数', max_length=500, null=True, verbose_name='参数')),
            ],
            options={
                'verbose_name': '子任务',
                'verbose_name_plural': '子任务',
                'ordering': ['-next_run'],
            },
        ),
        migrations.AlterModelOptions(
            name='jobs',
            options={'ordering': ['-create_date'], 'verbose_name': '任务列表', 'verbose_name_plural': '任务列表'},
        ),
        migrations.RemoveField(
            model_name='jobs',
            name='job_id',
        ),
        migrations.RemoveField(
            model_name='jobs',
            name='next_run',
        ),
        migrations.RemoveField(
            model_name='jobs',
            name='parameters',
        ),
        migrations.RemoveField(
            model_name='jobs',
            name='plan',
        ),
        migrations.AlterField(
            model_name='jobs',
            name='on_line',
            field=models.BooleanField(choices=[(True, '任务已经添加'), (False, '任务等待添加')], default=False, help_text='是否添加', verbose_name='是否添加'),
        ),
        migrations.AddField(
            model_name='job',
            name='job',
            field=models.ForeignKey(help_text='任务分类', on_delete=django.db.models.deletion.CASCADE, to='job.Jobs', verbose_name='任务分类'),
        ),
    ]
