# Generated by Django 2.1.5 on 2020-09-10 09:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('job', '0009_auto_20200910_1643'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='job',
            name='case_id',
        ),
        migrations.AlterField(
            model_name='job',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
