# Generated by Django 2.1.5 on 2020-09-10 09:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('job', '0010_auto_20200910_1703'),
    ]

    operations = [
        migrations.AddField(
            model_name='job',
            name='is_over',
            field=models.BooleanField(default=False, help_text='是否完成', verbose_name='是否完成'),
        ),
        migrations.AddField(
            model_name='jobs',
            name='is_over',
            field=models.BooleanField(default=False, help_text='是否全部完成', verbose_name='是否全部完成'),
        ),
    ]
