# Generated by Django 2.1.5 on 2020-09-10 10:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('job', '0011_auto_20200910_1741'),
    ]

    operations = [
        migrations.AddField(
            model_name='jobs',
            name='status',
            field=models.BooleanField(default=False, help_text='是否启动', verbose_name='是否启动'),
        ),
    ]
