# Generated by Django 2.1.5 on 2020-09-10 10:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('job', '0012_jobs_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='jobs',
            name='name',
            field=models.CharField(choices=[('send_mes', '发送订阅消息'), ('change_status', '修改状态'), ('test', '测试代码')], default='send_mes', help_text='任务名称，描述任务做什么的', max_length=200, unique=True, verbose_name='任务名称'),
        ),
    ]
