# Generated by Django 2.1.5 on 2020-09-11 11:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('job', '0013_auto_20200910_1845'),
    ]

    operations = [
        migrations.AddField(
            model_name='job',
            name='on_line',
            field=models.BooleanField(choices=[(True, '任务已经添加'), (False, '任务等待添加')], default=False, help_text='是否添加', verbose_name='是否添加'),
        ),
        migrations.AlterField(
            model_name='jobs',
            name='jobType',
            field=models.CharField(choices=[('date', '一次任务'), ('interval', '周期任务'), ('cron', 'corn任务')], default='date', help_text='任务类型', max_length=10, verbose_name='任务类型'),
        ),
        migrations.AlterField(
            model_name='jobs',
            name='name',
            field=models.CharField(choices=[('send_mes', '发送订阅消息'), ('change_status', '监听状态'), ('test', '测试代码')], default='send_mes', help_text='任务名称，描述任务做什么的', max_length=200, unique=True, verbose_name='任务名称'),
        ),
    ]
