# Generated by Django 2.1.5 on 2020-09-21 09:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('job', '0014_auto_20200911_1934'),
    ]

    operations = [
        migrations.AlterField(
            model_name='job',
            name='next_run',
            field=models.CharField(help_text='下次执行时间', max_length=100, null=True, verbose_name='下次执行时间'),
        ),
        migrations.AlterField(
            model_name='jobs',
            name='name',
            field=models.CharField(choices=[('send_mes', '发送订阅消息'), ('change_status', '监听状态'), ('test', '测试代码'), ('analyze_data', '分析数据')], default='send_mes', help_text='任务名称，描述任务做什么的', max_length=200, unique=True, verbose_name='任务名称'),
        ),
    ]
